version: '3.8'

services:
  antelligence:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      # API Keys - Required for LLM functionality
      - IO_SECRET_KEY=${IO_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      
      # Blockchain Configuration - Required for Sepolia integration
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - FOOD_ADDR=${FOOD_ADDR}
      - MEMORY_ADDR=${MEMORY_ADDR}
      
      # Production Environment
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./logs:/app/logs:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 